SUPABASE_URL = "https://tqynlhdygzstdfoupnbm.supabase.co/rest/v1/"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxeW5saGR5Z3pzdGRmb3VwbmJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODExNzQ5OTUsImV4cCI6MjA5Njc1MDk5NX0.xqLz4zszPxj4U3wnavSWV29qJGxCUEcqjvt3n_Xlzlw"
